import img from "../images/main_page/cardImg.jpg";


const cards = [
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 90,
    date: "2006-11-25",
    category: "paintings",
    id: 324,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 11,
    date: "2014-11-25",
    category: "posters",
    id: 256,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 105,
    date: "2016-11-25",
    category: "postcards",
    id: 3,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 34,
    date: "2015-11-25",
    category: "caps",
    id: 4,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 22,
    date: "2015-10-25",
    category: "t-shorts",
    id: 5,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 40,
    date: "2015-11-26",
    category: "bags",
    id: 6,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 1,
    date: "2012-01-25",
    category: "nft",
    id: 7,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 1050,
    date: "2003-10-25",
    category: "digital",
    id: 8,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 110,
    date: "2010-11-25",
    category: "nft",
    id: 9,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 20,
    date: "2010-08-25",
    category: "digital",
    id: 10,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 200,
    date: "2010-06-01",
    category: "t-shorts",
    id: 11,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 250,
    date: "2002-11-25",
    category: "postcards",
    id: 12,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 14,
    date: "2014-11-25",
    category: "postcards",
    id: 13,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 100,
    date: "2014-11-26",
    category: "paintings",
    id: 14,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 25,
    date: "2014-11-27",
    category: "paintings",
    id: 15,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 102,
    date: "2014-11-22",
    category: "paintings",
    id: 16,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 12,
    date: "2014-10-22",
    category: "paintings",
    id: 17,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 10,
    date: "2014-11-25",
    category: "paintings",
    id: 18,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 16,
    date: "2014-11-25",
    category: "t-shorts",
    id: 19,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 150,
    date: "2014-11-25",
    category: "t-shorts",
    id: 20,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 90,
    date: "2006-11-25",
    category: "paintings",
    id: 21,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 11,
    date: "2014-11-25",
    category: "posters",
    id: 22,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 105,
    date: "2016-11-25",
    category: "postcards",
    id: 23,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 34,
    date: "2015-11-25",
    category: "caps",
    id: 24,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 22,
    date: "2015-10-25",
    category: "t-shorts",
    id: 25,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 40,
    date: "2015-11-26",
    category: "bags",
    id: 26,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 1,
    date: "2012-01-25",
    category: "nft",
    id: 27,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 1050,
    date: "2003-10-25",
    category: "digital",
    id: 28,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 110,
    date: "2010-11-25",
    category: "nft",
    id: 29,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 20,
    date: "2010-08-25",
    category: "digital",
    id: 30,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 200,
    date: "2010-06-01",
    category: "t-shorts",
    id: 31,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 250,
    date: "2002-11-25",
    category: "postcards",
    id: 32,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 14,
    date: "2014-11-25",
    category: "postcards",
    id: 33,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 100,
    date: "2014-11-26",
    category: "paintings",
    id: 34,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 25,
    date: "2014-11-27",
    category: "paintings",
    id: 35,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 102,
    date: "2014-11-22",
    category: "paintings",
    id: 36,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 12,
    date: "2014-10-22",
    category: "paintings",
    id: 37,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 10,
    date: "2014-11-25",
    category: "paintings",
    id: 38,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 16,
    date: "2014-11-25",
    category: "t-shorts",
    id: 39,
    like: false,
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 150,
    date: "2014-11-25",
    category: "t-shorts",
    id: 40,
    like: false,
  },
];

export default cards