import img from "../images/main_page/cardImg.jpg";


const cards = [
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 90,
    date: "2006-11-25",
    category: "paintings",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 11,
    date: "2014-11-25",
    category: "posters",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 105,
    date: "2016-11-25",
    category: "postcards",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 34,
    date: "2015-11-25",
    category: "caps",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 22,
    date: "2015-10-25",
    category: "t-shorts",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 40,
    date: "2015-11-26",
    category: "bags",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 1,
    date: "2012-01-25",
    category: "nft",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 1050,
    date: "2003-10-25",
    category: "digital",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 110,
    date: "2010-11-25",
    category: "nft",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 20,
    date: "2010-08-25",
    category: "digital",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 200,
    date: "2010-06-01",
    category: "t-shorts",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 250,
    date: "2002-11-25",
    category: "postcards",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 14,
    date: "2014-11-25",
    category: "postcards",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 100,
    date: "2014-11-26",
    category: "paintings",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 25,
    date: "2014-11-27",
    category: "paintings",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 102,
    date: "2014-11-22",
    category: "paintings",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 12,
    date: "2014-10-22",
    category: "paintings",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 10,
    date: "2014-11-25",
    category: "paintings",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 16,
    date: "2014-11-25",
    category: "t-shorts",
  },
  {
    img: img,
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur, aut omnis id illo nisi facilis incidunt culpa saepe repellat neque quibusdam amet ducimus adipisci deserunt a accusantium est tenetur mollitia.",
    price: 150,
    date: "2014-11-25",
    category: "t-shorts",
  },
];

export default cards